package styles

import (
	"github.com/zhangdapeng520/zdpgo_pygments"
)

// Doom One style. Inspired by Atom One and Doom Emacs's Atom One theme
var DoomOne = Register(zdpgo_pygments.MustNewStyle("doom-one", zdpgo_pygments.StyleEntries{
	zdpgo_pygments.Text:                 "#b0c4de",
	zdpgo_pygments.Error:                "#b0c4de",
	zdpgo_pygments.Comment:              "italic #8a93a5",
	zdpgo_pygments.CommentHashbang:      "bold",
	zdpgo_pygments.Keyword:              "#c678dd",
	zdpgo_pygments.KeywordType:          "#ef8383",
	zdpgo_pygments.KeywordConstant:      "bold #b756ff",
	zdpgo_pygments.Operator:             "#c7bf54",
	zdpgo_pygments.OperatorWord:         "bold #b756ff",
	zdpgo_pygments.Punctuation:          "#b0c4de",
	zdpgo_pygments.Name:                 "#c1abea",
	zdpgo_pygments.NameAttribute:        "#b3d23c",
	zdpgo_pygments.NameBuiltin:          "#ef8383",
	zdpgo_pygments.NameClass:            "#76a9f9",
	zdpgo_pygments.NameConstant:         "bold #b756ff",
	zdpgo_pygments.NameDecorator:        "#e5c07b",
	zdpgo_pygments.NameEntity:           "#bda26f",
	zdpgo_pygments.NameException:        "bold #fd7474",
	zdpgo_pygments.NameFunction:         "#00b1f7",
	zdpgo_pygments.NameProperty:         "#cebc3a",
	zdpgo_pygments.NameLabel:            "#f5a40d",
	zdpgo_pygments.NameNamespace:        "#76a9f9",
	zdpgo_pygments.NameTag:              "#e06c75",
	zdpgo_pygments.NameVariable:         "#DCAEEA",
	zdpgo_pygments.NameVariableGlobal:   "bold #DCAEEA",
	zdpgo_pygments.NameVariableInstance: "#e06c75",
	zdpgo_pygments.Literal:              "#98c379",
	zdpgo_pygments.Number:               "#d19a66",
	zdpgo_pygments.String:               "#98c379",
	zdpgo_pygments.StringDoc:            "#7e97c3",
	zdpgo_pygments.StringDouble:         "#63c381",
	zdpgo_pygments.StringEscape:         "bold #d26464",
	zdpgo_pygments.StringHeredoc:        "#98c379",
	zdpgo_pygments.StringInterpol:       "#98c379",
	zdpgo_pygments.StringOther:          "#70b33f",
	zdpgo_pygments.StringRegex:          "#56b6c2",
	zdpgo_pygments.StringSingle:         "#98c379",
	zdpgo_pygments.StringSymbol:         "#56b6c2",
	zdpgo_pygments.Generic:              "#b0c4de",
	zdpgo_pygments.GenericEmph:          "italic",
	zdpgo_pygments.GenericHeading:       "bold #a2cbff",
	zdpgo_pygments.GenericInserted:      "#a6e22e",
	zdpgo_pygments.GenericOutput:        "#a6e22e",
	zdpgo_pygments.GenericUnderline:     "underline",
	zdpgo_pygments.GenericPrompt:        "#a6e22e",
	zdpgo_pygments.GenericStrong:        "bold",
	zdpgo_pygments.GenericSubheading:    "#a2cbff",
	zdpgo_pygments.GenericTraceback:     "#a2cbff",
	zdpgo_pygments.Background:           "#b0c4de bg:#282c34",
}))
