package styles

import (
	"github.com/zhangdapeng520/zdpgo_pygments"
)

// Dracula Style
var Dracula = Register(zdpgo_pygments.MustNewStyle("dracula", zdpgo_pygments.StyleEntries{
	zdpgo_pygments.Comment:                  "#6272a4",
	zdpgo_pygments.CommentHashbang:          "#6272a4",
	zdpgo_pygments.CommentMultiline:         "#6272a4",
	zdpgo_pygments.CommentPreproc:           "#ff79c6",
	zdpgo_pygments.CommentSingle:            "#6272a4",
	zdpgo_pygments.CommentSpecial:           "#6272a4",
	zdpgo_pygments.Generic:                  "#f8f8f2",
	zdpgo_pygments.GenericDeleted:           "#ff5555",
	zdpgo_pygments.GenericEmph:              "#f8f8f2 underline",
	zdpgo_pygments.GenericError:             "#f8f8f2",
	zdpgo_pygments.GenericHeading:           "#f8f8f2 bold",
	zdpgo_pygments.GenericInserted:          "#50fa7b bold",
	zdpgo_pygments.GenericOutput:            "#44475a",
	zdpgo_pygments.GenericPrompt:            "#f8f8f2",
	zdpgo_pygments.GenericStrong:            "#f8f8f2",
	zdpgo_pygments.GenericSubheading:        "#f8f8f2 bold",
	zdpgo_pygments.GenericTraceback:         "#f8f8f2",
	zdpgo_pygments.GenericUnderline:         "underline",
	zdpgo_pygments.Error:                    "#f8f8f2",
	zdpgo_pygments.Keyword:                  "#ff79c6",
	zdpgo_pygments.KeywordConstant:          "#ff79c6",
	zdpgo_pygments.KeywordDeclaration:       "#8be9fd italic",
	zdpgo_pygments.KeywordNamespace:         "#ff79c6",
	zdpgo_pygments.KeywordPseudo:            "#ff79c6",
	zdpgo_pygments.KeywordReserved:          "#ff79c6",
	zdpgo_pygments.KeywordType:              "#8be9fd",
	zdpgo_pygments.Literal:                  "#f8f8f2",
	zdpgo_pygments.LiteralDate:              "#f8f8f2",
	zdpgo_pygments.Name:                     "#f8f8f2",
	zdpgo_pygments.NameAttribute:            "#50fa7b",
	zdpgo_pygments.NameBuiltin:              "#8be9fd italic",
	zdpgo_pygments.NameBuiltinPseudo:        "#f8f8f2",
	zdpgo_pygments.NameClass:                "#50fa7b",
	zdpgo_pygments.NameConstant:             "#f8f8f2",
	zdpgo_pygments.NameDecorator:            "#f8f8f2",
	zdpgo_pygments.NameEntity:               "#f8f8f2",
	zdpgo_pygments.NameException:            "#f8f8f2",
	zdpgo_pygments.NameFunction:             "#50fa7b",
	zdpgo_pygments.NameLabel:                "#8be9fd italic",
	zdpgo_pygments.NameNamespace:            "#f8f8f2",
	zdpgo_pygments.NameOther:                "#f8f8f2",
	zdpgo_pygments.NameTag:                  "#ff79c6",
	zdpgo_pygments.NameVariable:             "#8be9fd italic",
	zdpgo_pygments.NameVariableClass:        "#8be9fd italic",
	zdpgo_pygments.NameVariableGlobal:       "#8be9fd italic",
	zdpgo_pygments.NameVariableInstance:     "#8be9fd italic",
	zdpgo_pygments.LiteralNumber:            "#bd93f9",
	zdpgo_pygments.LiteralNumberBin:         "#bd93f9",
	zdpgo_pygments.LiteralNumberFloat:       "#bd93f9",
	zdpgo_pygments.LiteralNumberHex:         "#bd93f9",
	zdpgo_pygments.LiteralNumberInteger:     "#bd93f9",
	zdpgo_pygments.LiteralNumberIntegerLong: "#bd93f9",
	zdpgo_pygments.LiteralNumberOct:         "#bd93f9",
	zdpgo_pygments.Operator:                 "#ff79c6",
	zdpgo_pygments.OperatorWord:             "#ff79c6",
	zdpgo_pygments.Other:                    "#f8f8f2",
	zdpgo_pygments.Punctuation:              "#f8f8f2",
	zdpgo_pygments.LiteralString:            "#f1fa8c",
	zdpgo_pygments.LiteralStringBacktick:    "#f1fa8c",
	zdpgo_pygments.LiteralStringChar:        "#f1fa8c",
	zdpgo_pygments.LiteralStringDoc:         "#f1fa8c",
	zdpgo_pygments.LiteralStringDouble:      "#f1fa8c",
	zdpgo_pygments.LiteralStringEscape:      "#f1fa8c",
	zdpgo_pygments.LiteralStringHeredoc:     "#f1fa8c",
	zdpgo_pygments.LiteralStringInterpol:    "#f1fa8c",
	zdpgo_pygments.LiteralStringOther:       "#f1fa8c",
	zdpgo_pygments.LiteralStringRegex:       "#f1fa8c",
	zdpgo_pygments.LiteralStringSingle:      "#f1fa8c",
	zdpgo_pygments.LiteralStringSymbol:      "#f1fa8c",
	zdpgo_pygments.Text:                     "#f8f8f2",
	zdpgo_pygments.TextWhitespace:           "#f8f8f2",
	zdpgo_pygments.Background:               " bg:#282a36",
}))
