package styles

import (
	"github.com/zhangdapeng520/zdpgo_pygments"
)

// GitHub style.
var GitHub = Register(zdpgo_pygments.MustNewStyle("github", zdpgo_pygments.StyleEntries{
	zdpgo_pygments.CommentMultiline:     "italic #999988",
	zdpgo_pygments.CommentPreproc:       "bold #999999",
	zdpgo_pygments.CommentSingle:        "italic #999988",
	zdpgo_pygments.CommentSpecial:       "bold italic #999999",
	zdpgo_pygments.Comment:              "italic #999988",
	zdpgo_pygments.Error:                "bg:#e3d2d2 #a61717",
	zdpgo_pygments.GenericDeleted:       "bg:#ffdddd #000000",
	zdpgo_pygments.GenericEmph:          "italic #000000",
	zdpgo_pygments.GenericError:         "#aa0000",
	zdpgo_pygments.GenericHeading:       "#999999",
	zdpgo_pygments.GenericInserted:      "bg:#ddffdd #000000",
	zdpgo_pygments.GenericOutput:        "#888888",
	zdpgo_pygments.GenericPrompt:        "#555555",
	zdpgo_pygments.GenericStrong:        "bold",
	zdpgo_pygments.GenericSubheading:    "#aaaaaa",
	zdpgo_pygments.GenericTraceback:     "#aa0000",
	zdpgo_pygments.GenericUnderline:     "underline",
	zdpgo_pygments.KeywordType:          "bold #445588",
	zdpgo_pygments.Keyword:              "bold #000000",
	zdpgo_pygments.LiteralNumber:        "#009999",
	zdpgo_pygments.LiteralStringRegex:   "#009926",
	zdpgo_pygments.LiteralStringSymbol:  "#990073",
	zdpgo_pygments.LiteralString:        "#d14",
	zdpgo_pygments.NameAttribute:        "#008080",
	zdpgo_pygments.NameBuiltinPseudo:    "#999999",
	zdpgo_pygments.NameBuiltin:          "#0086B3",
	zdpgo_pygments.NameClass:            "bold #445588",
	zdpgo_pygments.NameConstant:         "#008080",
	zdpgo_pygments.NameDecorator:        "bold #3c5d5d",
	zdpgo_pygments.NameEntity:           "#800080",
	zdpgo_pygments.NameException:        "bold #990000",
	zdpgo_pygments.NameFunction:         "bold #990000",
	zdpgo_pygments.NameLabel:            "bold #990000",
	zdpgo_pygments.NameNamespace:        "#555555",
	zdpgo_pygments.NameTag:              "#000080",
	zdpgo_pygments.NameVariableClass:    "#008080",
	zdpgo_pygments.NameVariableGlobal:   "#008080",
	zdpgo_pygments.NameVariableInstance: "#008080",
	zdpgo_pygments.NameVariable:         "#008080",
	zdpgo_pygments.Operator:             "bold #000000",
	zdpgo_pygments.TextWhitespace:       "#bbbbbb",
	zdpgo_pygments.Background:           " bg:#ffffff",
}))
