package styles

import (
	"github.com/zhangdapeng520/zdpgo_pygments"
)

// Murphy style.
var Murphy = Register(zdpgo_pygments.MustNewStyle("murphy", zdpgo_pygments.StyleEntries{
	zdpgo_pygments.TextWhitespace:        "#bbbbbb",
	zdpgo_pygments.Comment:               "#666 italic",
	zdpgo_pygments.CommentPreproc:        "#579 noitalic",
	zdpgo_pygments.CommentSpecial:        "#c00 bold",
	zdpgo_pygments.Keyword:               "bold #289",
	zdpgo_pygments.KeywordPseudo:         "#08f",
	zdpgo_pygments.KeywordType:           "#66f",
	zdpgo_pygments.Operator:              "#333",
	zdpgo_pygments.OperatorWord:          "bold #000",
	zdpgo_pygments.NameBuiltin:           "#072",
	zdpgo_pygments.NameFunction:          "bold #5ed",
	zdpgo_pygments.NameClass:             "bold #e9e",
	zdpgo_pygments.NameNamespace:         "bold #0e84b5",
	zdpgo_pygments.NameException:         "bold #F00",
	zdpgo_pygments.NameVariable:          "#036",
	zdpgo_pygments.NameVariableInstance:  "#aaf",
	zdpgo_pygments.NameVariableClass:     "#ccf",
	zdpgo_pygments.NameVariableGlobal:    "#f84",
	zdpgo_pygments.NameConstant:          "bold #5ed",
	zdpgo_pygments.NameLabel:             "bold #970",
	zdpgo_pygments.NameEntity:            "#800",
	zdpgo_pygments.NameAttribute:         "#007",
	zdpgo_pygments.NameTag:               "#070",
	zdpgo_pygments.NameDecorator:         "bold #555",
	zdpgo_pygments.LiteralString:         "bg:#e0e0ff",
	zdpgo_pygments.LiteralStringChar:     "#88F bg:",
	zdpgo_pygments.LiteralStringDoc:      "#D42 bg:",
	zdpgo_pygments.LiteralStringInterpol: "bg:#eee",
	zdpgo_pygments.LiteralStringEscape:   "bold #666",
	zdpgo_pygments.LiteralStringRegex:    "bg:#e0e0ff #000",
	zdpgo_pygments.LiteralStringSymbol:   "#fc8 bg:",
	zdpgo_pygments.LiteralStringOther:    "#f88",
	zdpgo_pygments.LiteralNumber:         "bold #60E",
	zdpgo_pygments.LiteralNumberInteger:  "bold #66f",
	zdpgo_pygments.LiteralNumberFloat:    "bold #60E",
	zdpgo_pygments.LiteralNumberHex:      "bold #058",
	zdpgo_pygments.LiteralNumberOct:      "bold #40E",
	zdpgo_pygments.GenericHeading:        "bold #000080",
	zdpgo_pygments.GenericSubheading:     "bold #800080",
	zdpgo_pygments.GenericDeleted:        "#A00000",
	zdpgo_pygments.GenericInserted:       "#00A000",
	zdpgo_pygments.GenericError:          "#FF0000",
	zdpgo_pygments.GenericEmph:           "italic",
	zdpgo_pygments.GenericStrong:         "bold",
	zdpgo_pygments.GenericPrompt:         "bold #c65d09",
	zdpgo_pygments.GenericOutput:         "#888",
	zdpgo_pygments.GenericTraceback:      "#04D",
	zdpgo_pygments.GenericUnderline:      "underline",
	zdpgo_pygments.Error:                 "#F00 bg:#FAA",
	zdpgo_pygments.Background:            " bg:#ffffff",
}))
