package styles

import (
	"github.com/zhangdapeng520/zdpgo_pygments"
)

// Tango style.
var Tango = Register(zdpgo_pygments.MustNewStyle("tango", zdpgo_pygments.StyleEntries{
	zdpgo_pygments.TextWhitespace:           "underline #f8f8f8",
	zdpgo_pygments.Error:                    "#a40000 border:#ef2929",
	zdpgo_pygments.Other:                    "#000000",
	zdpgo_pygments.Comment:                  "italic #8f5902",
	zdpgo_pygments.CommentMultiline:         "italic #8f5902",
	zdpgo_pygments.CommentPreproc:           "italic #8f5902",
	zdpgo_pygments.CommentSingle:            "italic #8f5902",
	zdpgo_pygments.CommentSpecial:           "italic #8f5902",
	zdpgo_pygments.Keyword:                  "bold #204a87",
	zdpgo_pygments.KeywordConstant:          "bold #204a87",
	zdpgo_pygments.KeywordDeclaration:       "bold #204a87",
	zdpgo_pygments.KeywordNamespace:         "bold #204a87",
	zdpgo_pygments.KeywordPseudo:            "bold #204a87",
	zdpgo_pygments.KeywordReserved:          "bold #204a87",
	zdpgo_pygments.KeywordType:              "bold #204a87",
	zdpgo_pygments.Operator:                 "bold #ce5c00",
	zdpgo_pygments.OperatorWord:             "bold #204a87",
	zdpgo_pygments.Punctuation:              "bold #000000",
	zdpgo_pygments.Name:                     "#000000",
	zdpgo_pygments.NameAttribute:            "#c4a000",
	zdpgo_pygments.NameBuiltin:              "#204a87",
	zdpgo_pygments.NameBuiltinPseudo:        "#3465a4",
	zdpgo_pygments.NameClass:                "#000000",
	zdpgo_pygments.NameConstant:             "#000000",
	zdpgo_pygments.NameDecorator:            "bold #5c35cc",
	zdpgo_pygments.NameEntity:               "#ce5c00",
	zdpgo_pygments.NameException:            "bold #cc0000",
	zdpgo_pygments.NameFunction:             "#000000",
	zdpgo_pygments.NameProperty:             "#000000",
	zdpgo_pygments.NameLabel:                "#f57900",
	zdpgo_pygments.NameNamespace:            "#000000",
	zdpgo_pygments.NameOther:                "#000000",
	zdpgo_pygments.NameTag:                  "bold #204a87",
	zdpgo_pygments.NameVariable:             "#000000",
	zdpgo_pygments.NameVariableClass:        "#000000",
	zdpgo_pygments.NameVariableGlobal:       "#000000",
	zdpgo_pygments.NameVariableInstance:     "#000000",
	zdpgo_pygments.LiteralNumber:            "bold #0000cf",
	zdpgo_pygments.LiteralNumberFloat:       "bold #0000cf",
	zdpgo_pygments.LiteralNumberHex:         "bold #0000cf",
	zdpgo_pygments.LiteralNumberInteger:     "bold #0000cf",
	zdpgo_pygments.LiteralNumberIntegerLong: "bold #0000cf",
	zdpgo_pygments.LiteralNumberOct:         "bold #0000cf",
	zdpgo_pygments.Literal:                  "#000000",
	zdpgo_pygments.LiteralDate:              "#000000",
	zdpgo_pygments.LiteralString:            "#4e9a06",
	zdpgo_pygments.LiteralStringBacktick:    "#4e9a06",
	zdpgo_pygments.LiteralStringChar:        "#4e9a06",
	zdpgo_pygments.LiteralStringDoc:         "italic #8f5902",
	zdpgo_pygments.LiteralStringDouble:      "#4e9a06",
	zdpgo_pygments.LiteralStringEscape:      "#4e9a06",
	zdpgo_pygments.LiteralStringHeredoc:     "#4e9a06",
	zdpgo_pygments.LiteralStringInterpol:    "#4e9a06",
	zdpgo_pygments.LiteralStringOther:       "#4e9a06",
	zdpgo_pygments.LiteralStringRegex:       "#4e9a06",
	zdpgo_pygments.LiteralStringSingle:      "#4e9a06",
	zdpgo_pygments.LiteralStringSymbol:      "#4e9a06",
	zdpgo_pygments.Generic:                  "#000000",
	zdpgo_pygments.GenericDeleted:           "#a40000",
	zdpgo_pygments.GenericEmph:              "italic #000000",
	zdpgo_pygments.GenericError:             "#ef2929",
	zdpgo_pygments.GenericHeading:           "bold #000080",
	zdpgo_pygments.GenericInserted:          "#00A000",
	zdpgo_pygments.GenericOutput:            "italic #000000",
	zdpgo_pygments.GenericPrompt:            "#8f5902",
	zdpgo_pygments.GenericStrong:            "bold #000000",
	zdpgo_pygments.GenericSubheading:        "bold #800080",
	zdpgo_pygments.GenericTraceback:         "bold #a40000",
	zdpgo_pygments.GenericUnderline:         "underline",
	zdpgo_pygments.Background:               " bg:#f8f8f8",
}))
